# Generated by Django 2.2 on 2019-05-15 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
